name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build & publish
        uses: docker/build-push-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          registry: registry.cn-hongkong.aliyuncs.com
          repository: mengli/nginx-rtmp-ffmpeg
          tags: latest
